spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fotpick?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234  # 본인 MySQL 비번
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: 1234

server:
  port: 8080